# Setup
title: Lee Vanrell
tagline: software engineering at his worst
email: leegvanrell@gmail.com
author: leeleegabriel
url: https://leeleegabriel.github.io
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
paginate: 1
baseurl: ""
permalink: pretty
host: 0.0.0.0

theme: plainwhite
plainwhite:
  name: Lee Vanrell
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  # generate social links in footer
  social_links:
    twitter: lee_vanrell
    github:  leevanrell
    linkedIn: in/leevanrell
    rss: rss

plugins:
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
sass:
  sass_dir: _sass
  style: :compressed
