author: lee vanrell
baseurl: ''
description: 'Software Engineer attempts to write a blog.  Focused on programming,
  3d printing, arduino''s, sdr, and more. '
email: leegvanrell@gmail.com
exclude: [.editorconfig, .git, .jekyll-cache, Gemfile, Gemfile.lock, LICENSE.md, README.md, node_modules]
host: 0.0.0.0
permalink: pretty
plainwhite:
  analytics_id: UA-156487363-1
  date_format: '%b %-d, %Y'
  name: Lee Vanrell
  navigation:
  - {title: About Me, url: /about}
  - {title: Bookmarks, url: /bookmarks}
  - {title: Subscribe, url: /feed.xml}
  show_excerpts: true
  sitemap: true
  social_links: {github: leevanrell, linkedIn: in/leevanrell, rss: rss, twitter: lee_vanrell}
  tagline: Software Engineer
gems: [jekyll-feed, jekyll-seo-tag, jekyll-scholar, jekyll-gist]
sass: {sass_dir: _sass, style: ':compressed'}
scholar: {style: mla}
show_excerpts: true
tagline: software engineering at his worst.
theme: plainwhite
title: Lee Vanrell
url: https://leevanrell.github.io
