# Setup
title: Lee Vanrell
tagline: software engineering at his worst
email: leegvanrell@gmail.com
author: leeleegabriel
url: https://leeleegabriel.github.io
description: > # this means to ignore newlines until "show_exerpts:"
  Software Engineer attempt to write a blog. 
  Focused on programming, 3d printing and design, arduino's and more.
show_excerpts: true # set to true to show excerpts on the homepage
paginate: 1
baseurl: ""
permalink: pretty
host: 0.0.0.0

theme: plainwhite
plainwhite:
  name: Lee Vanrell
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  social_links:
    twitter: lee_vanrell
    github:  leevanrell
    linkedIn: in/leevanrell
    rss: rss

# defaults:
#   - scope:
#       path: "assets/img"
#     values:
#       image: true

plugins:
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-gist
  #- jekyll-coffeescript
  #- jekyll-paginate

scholar:
  style: mla

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed
